# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 用户体验志
email: jop@live.cn
description: Jop's blog


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://uxfan.com" # the base hostname & protocol for your site
twitter_username: jopsay
weibo_username: jopz
weibo_nickname: 青春的猴小野
github_username:  supermonkeyz

# Build settings
markdown: kramdown
